# Generated by Django 3.1.4 on 2020-12-20 14:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('address', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=300)),
                ('state', models.CharField(max_length=300)),
                ('zipcode', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('price', models.IntegerField()),
                ('bedroom', models.IntegerField()),
                ('bedrooms', models.DecimalField(decimal_places=1, max_digits=2)),
                ('gerage', models.IntegerField(default=0)),
                ('saft', models.IntegerField()),
                ('lot_size', models.DecimalField(decimal_places=1, max_digits=5)),
                ('main_photo', models.ImageField(upload_to='listing_photo')),
                ('photo_1', models.ImageField(blank=True, upload_to='listing_photo')),
                ('photo_2', models.ImageField(blank=True, upload_to='listing_photo')),
                ('photo_3', models.ImageField(blank=True, upload_to='listing_photo')),
                ('photo_4', models.ImageField(blank=True, upload_to='listing_photo')),
                ('published', models.BooleanField(default=True)),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
