# Generated by Django 3.1.4 on 2020-12-20 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_auto_20201220_1601'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Listing',
        ),
    ]
