# Generated by Django 3.1.4 on 2021-01-21 11:55
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0006_auto_20210121_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='photo_5',
        ),
    ]
