# Generated by Django 3.1.4 on 2021-02-08 22:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0007_remove_listing_photo_5'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(default='+212', max_length=50)),
                ('message', models.TextField(blank=True)),
                ('contact_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('listing', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='realtors',
            name='phone',
            field=models.CharField(default='+212', max_length=30),
        ),
    ]
