# Generated by Django 3.1.4 on 2021-02-25 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0008_auto_20210208_2332'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contactform',
        ),
    ]
