# Generated by Django 3.1.4 on 2020-12-27 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_auto_20201227_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtors',
            name='phone',
            field=models.CharField(default='+212', max_length=20),
        ),
    ]
